li=[34,56,67,93,10,24,56,33,45]
print("the elements of list",li)
li.append(26)
print("to add element in last",li)
li.extend([39,20])
print('to add multiple element in list',li)
li.insert(4,78)
print("to insert the element",li)
li.pop()
print("to remove the last element",li)
li.pop(6)
print("remove the 6th element",li)
li.remove(33)
print("remove value in the list",li)
li.clear()
print(li)
#print("the minimun value of list",min(li))
del li
print(li)
'''print("the maximum value of list",max(li))
print("the sum of list value",sum(li))
print("count 56",li.count(56))
print("count 23",li.count(34))
print("type of li is",type(li))
print ("index",li.index(56))
li.reverse()
print ("reverse",li)

li.sort()
print("the asending order",li)
li.sort(reverse=True)
print(" the desending order",li)

print(li[1:4])
print(li[0:6:2])
print(li[:5])
print(li[4:])
li2 =['apple','orange','mango','grape','banana','mango']
print("the elemnt of list",li2)
print('count',li2.count('mango'))
print('type',type(li2))
print("index",li2.index('mango'))
li2.append('guva')
print('to add one value in last',li2)'''
  
