x=(1,23,45,78,90,23,35,56)
print(x)
print("type    ",type(x))
a=list(x)
print(a)
a.append(7)
print(a)
a.extend([24,18,22])
print("to add multiple element   ",a)
a.insert(5,7)
print(" to insert the element",a)
#remove element
a.pop()
print('to remove last  element',a)
a.pop(3)
print(a)
a.remove(1)
print("to remove value in the list",a)
a.clear()
print(a)
print('minimum value of a  ',min(a))
print('the maximum value of a  ',max(a))
print("sum of list",sum(a))
#a.reverse()
#print("reverse ",a)
a.sort()
print("the asending order of list",a)
a.sort(reverse=True)
print("the desending order of list",a)
print(a[2:6])
print(a[1:4:2])
print(a[:5])
print(a[3:])'''



